//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvProgramGuideApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;

    public partial class NepalChannelScheduleEntities : DbContext
    {
         public NepalChannelScheduleEntities()
            : base("name=NepalChannelScheduleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChannelCategory> ChannelCategories { get; set; }
        public DbSet<ChannelDetail> ChannelDetails { get; set; }
        public DbSet<Day> Days { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<ProgramCategory> ProgramCategories { get; set; }
        public DbSet<ProgramDetail> ProgramDetails { get; set; }
        public DbSet<ProgramTypeDetail> ProgramTypeDetails { get; set; }
        public DbSet<tblScheduleDetail> tblScheduleDetails { get; set; }
        public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int getallChannelName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getallChannelName");
        }
    
        public virtual int SaveChhannelName(string channelName)
        {
            var channelNameParameter = channelName != null ?
                new ObjectParameter("ChannelName", channelName) :
                new ObjectParameter("ChannelName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveChhannelName", channelNameParameter);
        }
    
        public virtual int updateImagePath(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateImagePath", idParameter, nameParameter);
        }
    }
}
