//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvProgramGuideApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pg_ChannelCategory
    {
        public pg_ChannelCategory()
        {
            this.pg_Channels = new HashSet<pg_Channels>();
        }
    
        public int SNo { get; set; }
        public string ChannelCategoryId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<pg_Channels> pg_Channels { get; set; }
    }
}
