//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvProgramGuideApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pg_Channels
    {
        public pg_Channels()
        {
            this.pg_ChannelSchedule = new HashSet<pg_ChannelSchedule>();
        }
    
        public string ChannelCategoryId { get; set; }
        public string ChannelId { get; set; }
        public string Name { get; set; }
        public string Logopath { get; set; }
    
        public virtual pg_ChannelCategory pg_ChannelCategory { get; set; }
        public virtual ICollection<pg_ChannelSchedule> pg_ChannelSchedule { get; set; }
    }
}
