//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvProgramGuideApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class cMind_ProgramGuideEntities : DbContext
    {
        public cMind_ProgramGuideEntities()
            : base("name=cMind_ProgramGuideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<pg_ChannelCategory> pg_ChannelCategory { get; set; }
        public DbSet<pg_Channels> pg_Channels { get; set; }
        public DbSet<pg_ChannelSchedule> pg_ChannelSchedule { get; set; }
        public DbSet<pg_Language> pg_Language { get; set; }
        public DbSet<pg_ProgramCategory> pg_ProgramCategory { get; set; }
        public DbSet<pg_Programs> pg_Programs { get; set; }
        public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int Insertchannel(string channelCategoryId, string name)
        {
            var channelCategoryIdParameter = channelCategoryId != null ?
                new ObjectParameter("ChannelCategoryId", channelCategoryId) :
                new ObjectParameter("ChannelCategoryId", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insertchannel", channelCategoryIdParameter, nameParameter);
        }
    
        public virtual int InsertChannelCategory(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertChannelCategory", nameParameter);
        }
    }
}
