//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvProgramGuideApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string ProgramName { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public Nullable<int> ProgramTypeId { get; set; }
        public bool isActive { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> ProgramLanguageId { get; set; }
    }
}
