//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvProgramGuideApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        public string ProgramCategoryId { get; set; }
        public string ProgramId { get; set; }
        public string Name { get; set; }
        public string LanguageId { get; set; }
        public string Logopath { get; set; }
        public string Remarks { get; set; }
    
        public virtual ProgramCategory pg_ProgramCategory { get; set; }
    }
}
