//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvProgramGuideApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<int> WeekDayId { get; set; }
        public Nullable<double> StartTime { get; set; }
        public Nullable<double> EndTime { get; set; }
        public System.DateTime programShowDate { get; set; }
        public string meridiem { get; set; }
        public decimal Id { get; set; }
        public Nullable<int> ChannelId { get; set; }
    }
}
